project:
  type: website
  resources:
    - CNAME

website:
  title: "marcocamilo"
  navbar:
    background: white
    foreground: black
    right:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - about.qmd
  page-footer: 
    left: "© 2024 Marco-Andrés Camilo-Pietri"
  bread-crumbs: false

format:
  html:
    # theme
    theme: 
      light: [default, assets/css/light-mods.scss]
      dark: [cyborg, assets/css/dark-mods.scss]
    css: assets/css/global.css
    # css: assets/css/styles.css
    # theme: 
    #   light: [default, assets/css/light-mods.scss]
    #   dark: cyborg
    # css: /assets/css/global.css
    toc: false
    lightbox: true
    
    # code blocks
    highlight-style: github
    code-block-border-left: true
    code-fold: true
    code-summary: View Code
    
    # includes
    include-in-header:
      - text: |
          <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

reference-location: margin
citation-location: margin


